name: Tag Release Workflow

on:
  push:
    tags:
      - '*' # Trigger on any tag push.
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  distribute-release:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    
    # Define variables at the job level
    env:
      COMPONENT_TYPE: "random-abstracted:index:PetAbstracted"
      PULUMI_ORG: "pequod"
      PULUMI_API_ENDPOINT: "https://api.pulumi.com"
      POLICY_GROUPS: '["default-policy-group", "goo-test"]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} # Checkout the specific tag that triggered the workflow
          fetch-depth: 0 # Ensures the build matches the git tag.

      # Uses Pulumi Cloud Github OIDC issuer
      # Note that if adding a new component and copying this code, you will need to update the
      # github oidc issuer stack that is used in the org to manage the issuers.
      - name: Authenticate to Pulumi
        uses: pulumi/auth-actions@v1
        with:
          organization: ${{ env.PULUMI_ORG }}
          requested-token-type: urn:pulumi:token-type:access_token:organization
          scope: admin  # Need admin privileges - the github oidc issuer is configured to allow this scope

      # Publish if this is a tag push.
      # Todo: Either deduce or use a variable for the pulumi org passed to the --publisher flag.
      - name: Publish Component to Pulumi Org
        if: github.event_name == 'push'
        run: |
          echo "Publishing latest component version to the ${{ env.PULUMI_ORG }} Pulumi org."
          pulumi package publish https://github.com/${{ github.repository }} --publisher ${{ env.PULUMI_ORG }}

      - name: Update Policy Config
        if: github.event_name == 'push'
        env:
          PULUMI_API_ENDPOINT: ${{ env.PULUMI_API_ENDPOINT }}
          PULUMI_ORG: ${{ env.PULUMI_ORG }}
          POLICY_GROUPS: ${{ env.POLICY_GROUPS }}
          # Use the tag as the component type and version.
          PULUMI_COMPONENT_TYPE_VERSIONS: '[{"${{ env.COMPONENT_TYPE }}": "${{ github.ref_name }}"}]'
        run: python ./.github/workflows/update-policy-config.py

      # Skip publishing if the workflow is manually triggered.
      - name: Manual run - Skip publishing
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "This is a manual workflow run."
          echo "Skipping component publishing to prevent accidental releases."
          echo "To publish, push a new tag instead of running manually."
