name: Tag Release Workflow

on:
  push:
    tags:
      - '*' # Trigger on any tag push.
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  distribute-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} # Checkout the specific tag that triggered the workflow
          fetch-depth: 0 # Ensures the build matches the git tag.

      - name: Show repository contents
        run: |
          echo "Current working directory: $(pwd)"
          echo "Git tag: ${{ github.ref_name }}"
          echo "Git commit: $(git rev-parse HEAD)"
          echo ""
          echo "Repository contents:"
          ls -la
          echo ""
          echo "Directory tree:"
          find . -type f -not -path './.git/*' | head -20

      - name: Publish Component to Pulumi Org
        if: github.event_name == 'push'
        run: |
          echo "Doing stuff"
          pulumi component publish --org my-org --name my-component --version ${{ github.ref_name }} --description "Release for tag ${{ github.ref_name }}"

      - name: Manual run - Skip publishing
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "This is a manual workflow run."
          echo "Skipping component publishing to prevent accidental releases."
          echo "To publish, push a new tag instead of running manually."
