name: Tag Release Workflow

on:
  push:
    tags:
      - '*' # Trigger on any tag push.
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  distribute-release:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} # Checkout the specific tag that triggered the workflow
          fetch-depth: 0 # Ensures the build matches the git tag.

      # Uses Pulumi Cloud Github OIDC issuer
      # Note that if adding a new component and copying this code, you will need to update the
      # github oidc issuer stack that is used in the org to manage the issuers.
      - name: Authenticate to Pulumi
        uses: pulumi/auth-actions@v1
        with:
          organization: pequod
          # requested-token-type: urn:pulumi:token-type:access_token:organization
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:mitch-pulumi-corp  # Replace YOUR_USERNAME with your actual Pulumi username

      # Publish if this is a tag push.
      # Todo: Either deduce or use a variable for the pulumi org passed to the --publisher flag.
      - name: Publish Component to Pulumi Org
        if: github.event_name == 'push'
        run: |
          echo "Publishing latest component version to the pequod Pulumi org."
          pulumi package publish https://github.com/${{ github.repository }} --publisher pequod

      # Skip publishing if the workflow is manually triggered.
      - name: Manual run - Skip publishing
        if: github.event_name == 'workflow_dispatch'
        env:
          PULUMI_API_ENDPOINT: "https://api.pulumi.com"
          PULUMI_ORG: "pequod"
          # In manual runs, we don't have a tag, so we use a placeholder component type and version.
          PULUMI_COMPONENT_TYPE_VERSIONS: '[{"random-abstracted:index:PetAbstracted": "1.0.0"}]'
          POLICY_GROUPS: '["platform-policies"]'  # JSON array string
        run: |
          echo "This is a manual workflow run."
          echo "Skipping component publishing to prevent accidental releases."
          echo "To publish, push a new tag instead of running manually."
          python ./.github/workflows/update-policy-config.py
